### ISSUE TITLE
Illegal option error when running script

### ISSUE THREAD

**Issue by netstx** [deajan/tcpping#10]
I get the following when trying to run tcpping, even after making the file executable:

```
# tcpping 
/usr/bin/tcpping: 74: set: Illegal option -o pipefail
```

Any ideas on how to fix this?

**Comment by deajan** [comment]
What OS / shell are you running ?

**Comment by netstx** [comment]
I tested on Debian 10.

**Comment by deajan** [comment]
Actually, you're not using bash, but dash, which does not have certain bash options.
I've commited a shell check in https://github.com/deajan/tcpping/commit/91996e3a3d830301016eb7f053de3be5c329ff5a

Feel free to test that version.
Another solution is to change the first line of the script to `#!/usr/bin/env bash`.

**Comment by netstx** [comment]
Thanks a lot, @deajan. The line change has fixed it, I will take a look at your commit also.
