### ISSUE TITLE
Tcpping output out of order

### ISSUE THREAD

**Issue by docast** [deajan/tcpping#16]
Hi,

We are executing tcpping as synthetic tests continuously and the configuratons used to run the test is listed below. We are executing tcpping for 5 minutes, which internally runs tcpping test 300 times, 1 sequence per second. 

The final output is generated from 300 sequences. We are processing the raw output generated for further processing.
For most part, we dont see any issue with the output file generated. But at times, the output seem to be not in order expected. Attached is one of the output for reference where line number 325 and 326 seem to be not in the order. Because of the order problem, we are facing issues in parsing the output generated. 
[tcpping_output_out_of_order.txt](https://github.com/deajan/tcpping/files/13639009/tcpping_output_out_of_order.txt)

Test Input Parameters:
                "test_target_params": [{
                        "ParamName": "-d",
                        "ParamValue": ""
                    },
                    {
                        "ParamName": "-x",
                        "ParamValue": "300"
                    },
                    {
                        "ParamName": "-r",
                        "ParamValue": "1 __server_ip__ 80"
                    }
                ]

Tcpping out of order:
![image](https://github.com/deajan/tcpping/assets/75414239/6b69f7e7-6dfa-4a2e-adfc-637bbe48df9a)

**Comment by deajan** [comment]
First of, sorry for the late reply.
I'm maintaining this project in my free time, of which I don't have much ^^ 

I don't really understand why the result is out of order, since there are no background jobs / threads involved, so output should be ordered.
What system do you run this on ? Which interpreter ?

**Comment by docast** [comment]
Generlaly we have seen that tcpping response comes in out of order, when the response for previous sequence comes after the next sequence. Lets say the ping response latency is >1 second, tcpping would have sent a new ping request with new sequence and since the response for the previous sequence is available after the initiation of next sequence, we are getting out of order issues. 

We are updating the way we process the tcpping output, thanks and this can be closed
