### ISSUE TITLE
Do the -n and -C options in the tcpping command result in no response?

### ISSUE THREAD

**Issue by xxhhlk** [deajan/tcpping#18]
### Issue:

When enabling both the -n and -C options in the tcpping command, which are intended to disable resolve IP addresses to their domain names and print in the same format as fping's -C option respectively, the command fails to receive any response from the target host.

### Expected Behavior:

Enabling the -n and -C options should not affect the ability to transmit and receive packets from the target host.

### Steps to Reproduce:

First, run the command without the -n option or without the -C option to confirm that the target host is reachable. (such as “tcpping -C www.bing.com ”).

Then run the command with both the -n and -C. (such as “tcpping -n -C www.bing.com ”).
Observe that no response is received from the target host.

### Additional Information:

	root@ser0604271324:~/smokeping# tcpping -n www.bing.com
	255  202.89.233.101  21.759 ms
	255  202.89.233.101  25.897 ms
	255  202.89.233.101  23.572 ms
	255  202.89.233.101  22.383 ms
	^C
	root@ser0604271324:~/smokeping# tcpping -C www.bing.com
	www.bing.com : 27.719 25.942 26.652 28.654 30.648^C
	root@ser0604271324:~/smokeping# tcpping -n -C  www.bing.com
	www.bing.com : - - - - -^C
	root@ser0604271324:~/smokeping# tcpping -C -n  www.bing.com
	www.bing.com : - - - - -^C

Operating System: Ubuntu 22.04.4 LTS
tcpping Version: tcpping v2.5dev Richard van den Berg <richard@vdberg.org>, Orsiris de Jong <ozy@netpower.fr>
traceroute Version: Modern traceroute for Linux, version 2.1.0

If you need any further information, please let me know.

**Comment by deajan** [comment]
The `-n` parameters changes traceroute's output, which wasn't catched properly.
Thanks for reporting, and sorry for the fix delay.

**Comment by r2ixuz** [comment]
May I ask why -n isn't default for any traceroute command? It makes no sense to me to reverse lookup every hop and it unnecessarily utilizes DNS servers. Furthermore it takes much more time to complete the Probes.
