### ISSUE TITLE
doesnt work without root or sudo

### ISSUE THREAD

**Issue by umlaeute** [deajan/tcpping#19]
this is a reboot of #2 

i'm trying to use `tcpping` together with `smokeping`.
as per resolution of #2, `tcpping` now takes a `-Z` flag to run as `sudo`, which works great.

unfortunately, i don't really see how this helps me, as `smokeping` does not allow me to specify any arguments to `tcpping` (instead `smokeping` relies on the `tcpping` binary to be setuid root, which of course doesn't work with shell-scripts).

it would be great if I could set the default flags of `tcpping` via some configuration script, e.g. `/etc/default/tcpping`:
```sh
EXTRA_OPTS='-Z'
```

(my current solution is to to just hack the `tcpping` script to always use `sudo`, but I'd rather not diverge from the upstream script.)

**Comment by deajan** [comment]
Hmmm. Fair enough. I'd just not put this in `/etc/default/tcpping` but rather `/etc/tcpping.conf`
Befor creating this file (which will only contain a single line, any other things that should be configurable ?

**Comment by umlaeute** [comment]
not for now :-)

but i guess, if we can specify arbitrary extra options via this file, then we can configure `tcpping` any way we like (as the cmdline options can configure all of the behaviour).

or would you rather have specific lines like this?
```sh
USE_SUDO=yes
```

**Comment by deajan** [comment]
Btw, you could typically resolve this with a bashrc file containing something alike `alias tcpping=tcpping -Z`.
Have you tried this perhaps ? It looks more elegant than fiddling around with a conf file for a small bash script ;)

**Comment by umlaeute** [comment]
i haven't tried, but `smokeping` calls the script directly, so I don't think that `.bashrc` would ever be executed (as there's no interactive shell)

**Comment by deajan** [comment]
Implemented, please have a look at current master.

**Comment by umlaeute** [comment]
in theory this looks good.

in practive, `source` is not POSIX compliant but a bashism (and a zshism).
on my Debian system, `/bin/sh` is a symlink to `dash`, which i think is stricter is this respect, and I get an error:
```
./tcpping: 89: source: not found
```

So https://github.com/deajan/tcpping/blob/471b972f012e16f2f341c9a1f02b5feb0abadb1d/tcpping#L88-L89 should probably be
```sh
[ -f "/etc/tcpping.conf" ] && . "/etc/tcpping.conf"
[ -f "./tcpping.conf" ] && . "./tcpping.conf" 
```

alternatively fix the shebang, but I would prefer a POSIX compliant solution.

---

there's actually a number of non-POSIX lines in the code:

```sh
$ checkbashisms tcpping
possible bashism in tcpping line 82 ($BASH_SOMETHING):
[ -n "$BASH_VERSION" ] && set -o pipefail
possible bashism in tcpping line 88 (should be '.', not 'source'):
[ -f "/etc/tcpping.conf" ] && source "/etc/tcpping.conf"
possible bashism in tcpping line 89 (should be '.', not 'source'):
[ -f "./tcpping.conf" ] && source "./tcpping.conf"
possible bashism in tcpping line 180 (type):
	if ! type awk > /dev/null 2>&1; then
possible bashism in tcpping line 185 (type):
	if type traceroute > /dev/null 2>&1; then
possible bashism in tcpping line 186 (type):
		traceRouteBinary=`type traceroute | awk '{print $(NF)}'`
possible bashism in tcpping line 197 (type):
	if type tcptraceroute > /dev/null 2>&1; then
possible bashism in tcpping line 198 (type):
		traceRouteBinary=`type tcptraceroute  | awk '{print $(NF)}'`
```

i guess the `type` invocations schould be replaced with `command -v`
the `BASH_VERSION`  check is "safe", but it in means, that with my dash-`sh`, pipefile if not set.

**Comment by deajan** [comment]
So indeed there's `source` which is a bashism, fixed.

As for `set -o pipefail`, only dash after [this](https://git.kernel.org/pub/scm/utils/dash/dash.git/commit/?id=6347b9fc52d742f36a0276cdea06cd9ad1f02c77) commit supports that option, so I'll have to hardpass here, since dash only introduced it a couple of months ago... I've already researched this before.

`type` command has been tested on all the supported shells (including dash), I'll stick with that one.

Have a look at current master.

**Comment by deajan** [comment]
Any thoughts before I make a release of this ?

**Comment by umlaeute** [comment]
the `sudo` problem seems to be solved fine.
i just opened another (minor) issue (#20), that you might want to tackle before doing a release.

**Comment by deajan** [comment]
Thanks for reporting back.
