### ISSUE TITLE
doesnt work without root or sudo

### ISSUE THREAD

**Issue by ausfestivus** [deajan/tcpping#2]
Morning,

Attempted to use this new script on an Ubuntu 16.04.5 LTS VM and it was producing zero output for smokeping. Debugged it down to the use of the `-T` switch with `traceroute` and the fact that the user `smokeping` runs as is just a normal user. User `smokeping` cant `sudo` and `traceroute` isnt setuid root by default.

Some more detailed notes:
* running as normal user
```
ubuntu@jump00:~$ /usr/local/bin/tcpping.new -C -x 5 220.233.82.46 5060
220.233.82.46 : - - - - -
ubuntu@jump00:~$ /usr/local/bin/tcpping -C -x 5 220.233.82.46 5060
220.233.82.46 : 13.097 14.740 14.146 13.350 13.738
```

* running with sudo
```
ubuntu@jump00:~$ sudo /usr/local/bin/tcpping.new -C -x 5 220.233.82.46 5060
220.233.82.46 : 13.349 12.796 13.697 13.730 13.162
ubuntu@jump00:~$ sudo /usr/local/bin/tcpping -C -x 5 220.233.82.46 5060
220.233.82.46 : 13.541 13.498 13.544 13.676 13.818
```

```
ubuntu@jump00:~$ /usr/local/bin/tcpping.new -z -C -x 5 220.233.82.46 5060
traceroute -T -f 255 -m 255 -q 1 -w 3  -p 5060 220.233.82.46
traceroute -T -f 255 -m 255 -q 1 -w 3  -p 5060 220.233.82.46
```

```
ubuntu@jump00:~$ traceroute -T -f 255 -m 255 -q 1 -w 3  -p 5060 220.233.82.46
You do not have enough privileges to use this traceroute method.
socket: Operation not permitted
```

**Comment by notjames** [comment]
At the very least, perform a check that will show an error message if permissions disallow the runtime to work. For instance, I just had this happen to me and I had to run some debugging to see why iwas getting blank, but obvious output:

```
~/projects/src/tcpping$ tcpping 8.8.8.8 53



^C
~/projects/src/tcpping$ 
```

Just submitted a PR to error if `sudo` us required.

**Comment by deajan** [comment]
Issue resolved by @notjames
