### ISSUE TITLE
timestamps are on a separate line

### ISSUE THREAD

**Issue by umlaeute** [deajan/tcpping#20]
adding `-d` to get timestamps gives me this output:

```
$ tcpping -d github.com 80
Wed Oct 30 12:30:53 CET 2024
seq 0: tcp response from lb-140-82-121-4-fra.github.com (140.82.121.4)  14.540 ms
Wed Oct 30 12:30:53 CET 2024
seq 1: tcp response from lb-140-82-121-4-fra.github.com (140.82.121.4)  14.680 ms
Wed Oct 30 12:30:54 CET 2024
seq 2: tcp response from lb-140-82-121-4-fra.github.com (140.82.121.4)  14.404 ms
```

this makes it a bit complicated to get timestamp and timing information in a parsable (and readable!) way.
I would have expected the timestamp to be on the same line as the actual information:

```
$ tcpping -d github.com 80
Wed Oct 30 12:30:53 CET 2024 seq 0: tcp response from lb-140-82-121-4-fra.github.com (140.82.121.4)  14.540 ms
Wed Oct 30 12:30:53 CET 2024 seq 1: tcp response from lb-140-82-121-4-fra.github.com (140.82.121.4)  14.680 ms
Wed Oct 30 12:30:54 CET 2024 seq 2: tcp response from lb-140-82-121-4-fra.github.com (140.82.121.4)  14.404 ms
```

**Comment by umlaeute** [comment]
i just noticed that in "columned" mode  (`-c`; besides i think the description should be changed from "columned" to "computer parsable"), the timestamp is present as a seconds-since-epoch value in the same line.
that kind of fixes the problem with "computer parsable output", though i still think that humans should be treated as first-class citizens as well :-)

i also note that in if i give both `-c` and `-d`, the output is multi-line and redundant:
```
$ tcpping -c -d github.com 80
Wed Oct 30 12:36:07 CET 2024
0 1730288167 19.219 github.com
Wed Oct 30 12:36:07 CET 2024
1 1730288167 15.013 github.com
Wed Oct 30 12:36:08 CET 2024
2 1730288168 14.341 github.com
```

i think in this case it would be better to leave out the human-readable date altogether. (probably printing a warning to stderr, indicating that the timestamp is present anyhow)

**Comment by deajan** [comment]
Indeed timestamps are on separate line, but this project inherits from Richard van den Berg's initial tcpping v1 implementation from 2002, and aims to keep as much retrocompatibility as possible to that version, so one does not simply change the output specs.

**Comment by umlaeute** [comment]
ah i see. i didn't know about the compat layer.

feel free to close this as "won't fix", if you want to.
