### ISSUE TITLE
Unable to run 'sudo traceroute -M.."

### ISSUE THREAD

**Issue by suagrXu** [deajan/tcpping#7]
Hello,thank you for this program!
my environment is "Linux version 4.4.162 (gcc version 5.3.0 (GCC) )"
i execute "tcpping -Z www.baidu.com"
then shell shows"
Unable to run 'sudo traceroute -M tcp -f 255 -m 255 -q 1 -w 3  -p 80 www.baidu.com' command. Please submit an issue in 'https://github.com/deajan/tcpping/issues' ".

**Comment by deajan** [comment]
Hmmm...  What does the command say when you run it directly ?
Are you allowed to sudo with your current user ?

**Comment by suagrXu** [comment]
oh,sorry,my enviroment is a  embedded copped linux.and it did not install "sudo",which used in the source code.
