### ISSUE TITLE
trap: SIGQUIT: bad trap

### ISSUE THREAD

**Issue by nobody-65534** [deajan/tcpping#8]
[Line 323](https://github.com/deajan/tcpping/blob/aed9b8049b987e684d3b2ea111c28a1d5d956494/tcpping#L323) `SIGQUIT` should be changed to `QUIT`, or it causes `trap: SIGQUIT: bad trap` when `-o` argument presented. 
Explanation [here](https://mywiki.wooledge.org/SignalTrap)

**Comment by deajan** [comment]
Thanks for the catch.
